spring.application.name=back

# Server
server.port=8080

# Database(????, ????????, ???, ????)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# allowPublicKeyRetrieval=true&useSSL=false ? ?? ?? ? ?? ??? ?????.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# JPA(Entity? ??? ?????? ??)
spring.jpa.hibernate.ddl-auto=update
# JPA? ??? ?????? ????(MySQL? ???? ?)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# SQL ??? ???? ??? ?? (??? ??!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# DevTools
# Java ??? ???? ??? ???
spring.devtools.restart.enabled=true


# Swagger UI ?? ?? ?? (???? /swagger-ui/index.html)
springdoc.swagger-ui.path=/swagger-ui.html

# API ?? ?? ?? ??
springdoc.api-docs.path=/api-docs

# ????? ??? ?? ?? ? ??
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json